"""Add user relationship to Donation

Revision ID: ceb6787dee29
Revises: 71d1994130ed
Create Date: 2024-03-13 10:15:51.581146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb6787dee29'
down_revision = '71d1994130ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_charityproject_name'), ['name'])

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_donation_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_donation_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_charityproject_name'), type_='unique')

    # ### end Alembic commands ###
